---
- hosts: localhost
  connection: local

  vars:
    osx_script: "~/.osx"
    setup_dir: "~/setup"

    # Ensure Ansible is installed via pip
    ansible_install_method: pip

    omz_git_repository: "https://github.com/ohmyzsh/ohmyzsh.git"
    omz_install_path: ~/.oh-my-zsh

  vars_files:
    - vars/other-package-managers.yml
    - vars/homebrew.yml
    - vars/dockutil.yml
    - vars/dotfiles.yml
    - vars/mas.yml

  pre_tasks:
    - name: Ensure folder for setup exists
      file:
        path: "{{ setup_dir }}/"
        state: directory
        mode: 0744

  roles:
    - elliotweiser.osx-command-line-tools
    - geerlingguy.ansible
    - geerlingguy.mac.homebrew

  tasks:
    - name: Update pkg_mgr fact after installing Homebrew
      ansible.builtin.setup:
        filter:
          - 'ansible_pkg_mgr'
    - name: Setup Terminal
      include_tasks: tasks/terminal.yml
      tags:
        - terminal
    - name: Setup VS Code
      include_tasks: tasks/vscode.yml
      tags:
        - terminal
    - name: Run Dotfile role.
      include_role:
        name: geerlingguy.dotfiles
    - name: Run .osx script
      command: "sudo sh {{ osx_script }}  --no-restart"
      changed_when: false
    - name: Run Mac Dock role.
      include_role:
        name: geerlingguy.mac.dock
    - name: Ensure an SSH key exists.
      community.crypto.openssh_keypair:
        path: "~/.ssh/id_ed25519"
        type: ed25519
    - include_tasks: tasks/rosetta.yml
      tags:
        - rosetta
