---
- hosts: localhost
  connection: local

  vars:
    osx_script: "~/.osx"
    setup_dir: "~/setup"

    # Ensure Ansible is installed via pip
    ansible_install_method: pip

    omz_git_repository: "https://github.com/ohmyzsh/ohmyzsh.git"
    omz_install_path: ~/.oh-my-zsh

  vars_files:
    - vars/other-package-managers.yml
    - vars/homebrew.yml
    - vars/dockutil.yml
    - vars/dotfiles.yml
    - vars/mas.yml

  pre_tasks:
    - name: Ensure folder for setup exists
      file:
        path: "{{ setup_dir }}/"
        state: directory
        mode: 0744
    - name: Ensure Rosetta is enabled. # We do this near the start as some Homebrew packages require Rosetta
      include_tasks: tasks/rosetta.yml
      tags:
        - rosetta

  roles:
    - elliotweiser.osx-command-line-tools
    - geerlingguy.ansible
    - geerlingguy.mac.homebrew

  tasks:
    - name: Update pkg_mgr fact after installing Homebrew
      ansible.builtin.setup:
        filter:
          - "ansible_pkg_mgr"
      # https://docs.brew.sh/FAQ#my-mac-apps-dont-find-homebrew-utilities
    - name: Ensure Mac apps can access Homebrew apps (fix for Android Studio)
      command: sudo launchctl config user path "$(brew --prefix)/bin:${PATH}"
    - name: Setup Terminal
      include_tasks:
        file: tasks/terminal.yml
        apply:
          tags: terminal
      tags:
        - terminal
    - name: Setup VS Code
      include_tasks:
        file: tasks/vscode.yml
        apply:
          tags: terminal
      tags:
        - terminal

    - name: Run Dotfile role.
      include_role:
        name: geerlingguy.dotfiles
    - name: Run .osx script
      command: "sudo sh {{ osx_script }}  --no-restart"
      changed_when: false
    - name: Run Mac Dock role.
      include_role:
        name: geerlingguy.mac.dock
