---
- hosts: localhost
  connection: local

  vars_files:
    - vars/other-package-managers.yml
    - vars/homebrew.yml
    - vars/dockutil.yml
    - vars/mas.yml

  pre_tasks:
    - name: Ensure folder for setup exists
      become: false
      file:
        path: ~/setup/
        state: directory
        mode: 0777

  vars:
    osx_script: "~/.osx --no-restart"

    # Ensure Ansible is installed via pip
    ansible_install_method: pip

    omz_install_script_location: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"

  roles:
    - elliotweiser.osx-command-line-tools
    - geerlingguy.ansible
    - geerlingguy.mac.homebrew

  tasks:
    - name: Install Oh My Zsh
      command: sh -c "$(curl -fsSL {{ omz_install_script_location }} )" "" --unattended
      register: omzinstall
      changed_when: omzinstall.rc != 0
    - name: Run App Store role
      include_role:
        name: geerlingguy.mac.mas
    - name: Run Dotfile role
      include_role:
        name: geerlingguy.dotfiles
    - name: Run Mac Dock role
      include_role:
        name: geerlingguy.mac.dock
    - name: Ensure an SSH key exists
      openssh_keypair:
        path: "~/.ssh/id_ed25519"
        type: ed25519
