- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    osx_script: "~/.osx --no-restart"

    mas_installed_app_ids:
      - 497799835    # Xcode

    homebrew_installed_packages:
      - node
      - nvm
      - redis
      - ssh-copy-id
      - pv

    homebrew_cask_apps:
      - docker
      - firefox
      - google-chrome
      - vlc

  roles:
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.mas
