---
- hosts: localhost
  connection: local

  vars:
    osx_script: "~/.osx --no-restart"
    setup_dir: "~/setup"

    # Ensure Ansible is installed via pip
    ansible_install_method: pip

    omz_git_repository: "https://github.com/ohmyzsh/ohmyzsh.git"
    omz_install_path: ~/.oh-my-zsh

  vars_files:
    - vars/other-package-managers.yml
    - vars/homebrew.yml
    - vars/dockutil.yml
    - vars/dotfiles.yml
    - vars/mas.yml

  pre_tasks:
    - name: Ensure folder for setup exists
      file:
        path: "{{ setup_dir }}/"
        state: directory
        mode: 0744

  roles:
    - elliotweiser.osx-command-line-tools
    - geerlingguy.ansible
    - geerlingguy.mac.homebrew
    - role: gantsign.visual-studio-code-extensions
      users:
        - username: "{{ lookup('env','USER') }}"
          visual_studio_code_extensions:
            - golang.go
            - kddejong.vscode-cfn-lint
            - redhat.vscode-yaml
            - tomaciazek.ansible
            - vscode.docker
            - vscode.yaml
            - miguelsolorio.fluent-icons
            - ms-vscode-remote.remote-ssh
            - ms-vscode-remote.remote-ssh-edit
            - ms-vscode-remote.remote-wsl
            - shardulm94.trailing-spaces

  tasks:
    - include_tasks: tasks/terminal.yml
      tags:
        - terminal

    - name: Run Dotfile role.
      include_role:
        name: geerlingguy.dotfiles
    - name: Run Mac Dock role.
      include_role:
        name: geerlingguy.mac.dock
    - name: Ensure an SSH key exists.
      community.crypto.openssh_keypair:
        path: "~/.ssh/id_ed25519"
        type: ed25519

    - include_tasks: tasks/rosetta.yml
      tags:
        - rosetta
