---
- hosts: localhost
  connection: local

  vars:
    osx_script: "~/.osx --no-restart"
    setup_dir: "~/setup"

    # Ensure Ansible is installed via pip
    ansible_install_method: pip

    omz_git_repository: "https://github.com/ohmyzsh/ohmyzsh.git"
    omz_install_path: ~/.oh-my-zsh

  vars_files:
    - vars/other-package-managers.yml
    - vars/homebrew.yml
    - vars/dockutil.yml
    - vars/dotfiles.yml
    - vars/mas.yml

  pre_tasks:
    - name: Ensure folder for setup exists
      file:
        path: "{{ setup_dir }}/"
        state: directory
        mode: 0744

  roles:
    - elliotweiser.osx-command-line-tools
    - geerlingguy.ansible
    - geerlingguy.mac.homebrew

  tasks:
    - name: Check if Oh My Zsh is installed.
      stat:
        path: "~/.oh-my-zsh"
      register: ohmyzsh_present
    - name: Download Oh My Zsh script.
      get_url: 
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: "{{ setup_dir }}/install-oh-my-zsh.sh"
        mode: 0744
      when: not ohmyzsh_present.stat.exists
    - name: Run Oh My Zsh script in unattended mode.
      command: 'sh {{ setup_dir }}/install-oh-my-zsh.sh "" --unattended'
      when: not ohmyzsh_present.stat.exists

    - name: Run Dotfile role.
      include_role:
        name: geerlingguy.dotfiles
    - name: Run Mac Dock role.
      include_role:
        name: geerlingguy.mac.dock
    - name: Ensure an SSH key exists.
      openssh_keypair:
        path: "~/.ssh/id_ed25519"
        type: ed25519
