---
roles:
  - name: geerlingguy.ansible
  - name: geerlingguy.pip
  - name: elliotweiser.osx-command-line-tools
  - name: geerlingguy.dotfiles
  - name: gantsign.visual-studio-code-extensions

collections:
  - name: geerlingguy.mac
  - name: community.crypto
