---
- name: Check if Oh My Zsh is installed.
  stat:
    path: "~/.oh-my-zsh"
  register: ohmyzsh_present
- name: Download Oh My Zsh script.
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: "{{ setup_dir }}/install-oh-my-zsh.sh"
    mode: 0744
  when: not ohmyzsh_present.stat.exists
- name: Run Oh My Zsh script in unattended mode.
  command: 'sh {{ setup_dir }}/install-oh-my-zsh.sh "" --unattended'
  when: not ohmyzsh_present.stat.exists
- name: Ensure zsh-autosuggestions is installed
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    version: master
- name: Ensure zsh-completions is installed
  git:
    repo: https://github.com/zsh-users/zsh-completions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
    version: master
- name: Ensure zsh-syntax-highlighting is installed
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    version: master
- name: Download iTerm2 shell integration script
  get_url:
    url: https://iterm2.com/shell_integration/install_shell_integration_and_utilities.sh
    dest: ~/.iterm2_shell_integration.sh
    mode: 0755

- name: Install iTerm2 shell integration
  command: ~/.iterm2_shell_integration.sh

- name: Ensure nvm is installed
  git:
    repo: https://github.com/nvm-sh/nvm.git
    dest: ~/.nvm
    version: master

- name: Ensure gh command completion is installed
  command: gh completion -s zsh > ~/.oh-my-zsh/custom/plugins/zsh-completions/src/_gh

# https://www.matscloud.com/blog/2020/06/25/how-to-use-aws-cdk-with-aws-sso-profiles/
- name: Ensure AWS SSO fix file is downloaded
  get_url:
    # Clone my fork of the linked Python script
    url: https://gist.githubusercontent.com/Rooster212/e11f2c9f28ff44d4def8a9cdc5af2a58/raw/59929e42881711b5a0e21d44a7a7267c45820b87/aws_sso.py
    dest: "~/.aws_sso.py"
    mode: 0744

# https://labbots.com/enabling-touch-id-for-access-on-terminal/
# - name: Enable TouchID support for sudo
#   lineinfile:
#     path: /etc/pam.d/sudo
#     line: auth sufficient pam_tid.so
#     state: present
#   tags:
#    - terminal
