---
- name: Ensure wanted VS Code extensions are installed
  import_role:
    name: gantsign.visual-studio-code-extensions
  vars:
    users:
      - username: "{{ lookup('env','USER') }}"
        visual_studio_code_extensions:
          - kddejong.vscode-cfn-lint
          - kisstkondoros.vscode-codemetrics
          - dbaeumer.vscode-eslint
          - miguelsolorio.fluent-icons
          - eamodio.gitlens
          - golang.go
          - vespa-dev-works.jestRunIt
          - ms-vsliveshare.vsliveshare-pack
          - esbenp.prettier-vscode
          - mechatroner.rainbow-csv
          - ms-vscode-remote.remote-ssh
          - ms-vscode-remote.remote-ssh-edit
          - ms-vscode-remote.remote-wsl
          - shardulm94.trailing-spaces
          - amodio.tsl-problem-matcher
